/* eslint-disable */
// WARNING: Do not edit this file

const ebconfig = {
  "integration": "react-1-ikRMCdIgfbbE-wja5mKQunqXBG2IoO3LOgItTGYCZyDPV1p00iq1D-gcPJed3kXXPFaK4ncEtp1y8OwKK2z9fPxPREfYVBjrMDp1NyBMcJ3GOq-9CBn-DVeM",
  "tt": "tt-1-CtQpxmMdmUK2vsEVFKFw0HM7hS4ZgMKS58lZSo7I-HM=",
  "version": "2020-11-20"
}

export default ebconfig;